;;; org-visibility-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-visibility.el

(autoload 'org-visibility-remove "org-visibility" "\
Remove visibility state of FILE-NAME or `current-buffer'.

(fn &optional FILE-NAME)" t)
(autoload 'org-visibility-clean "org-visibility" "\
Remove any missing files from `org-visibility-state-file'." t)
(autoload 'org-visibility-save "org-visibility" "\
Save visibility state if buffer has been modified.

If NOERROR is non-nil, do not throw errors.

If FORCE is non-nil, save even if file is not marked as dirty.

(fn &optional NOERROR FORCE)" t)
(autoload 'org-visibility-force-save "org-visibility" "\
Save visibility state even if buffer has not been modified." t)
(autoload 'org-visibility-save-all-buffers "org-visibility" "\
Save visibility state for any modified buffers, ignoring errors.

If FORCE is non-nil, save even if files are not marked as dirty.

(fn &optional FORCE)" t)
(autoload 'org-visibility-load "org-visibility" "\
Load FILE or `current-buffer' and restore its visibility state, ignoring errors.

(fn &optional FILE)" t)
(defvar org-visibility-mode nil "\
Non-nil if Org-visibility mode is enabled.
See the `org-visibility-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `org-visibility-mode'.")
(custom-autoload 'org-visibility-mode "org-visibility" nil)
(autoload 'org-visibility-mode "org-visibility" "\
Minor mode for toggling `org-visibility' hooks on and off.

This minor mode will persist (save and load) the state of the
visible sections of `org-mode' files. The state is saved when the
file is saved or killed, and restored when the file is loaded.

\\{org-visibility-mode-map}

This is a global minor mode.  If called interactively, toggle the
`Org-visibility mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='org-visibility-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "org-visibility" '("org-visibility"))

;;; End of scraped data

(provide 'org-visibility-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-visibility-autoloads.el ends here
