;;; calibre-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from calibre.el

(register-definition-prefixes "calibre" '("calibre-"))


;;; Generated autoloads from calibre-book.el

(register-definition-prefixes "calibre-book" '("calibre-"))


;;; Generated autoloads from calibre-cli.el

(register-definition-prefixes "calibre-cli" '("calibre-cli--"))


;;; Generated autoloads from calibre-core.el

(register-definition-prefixes "calibre-core" '("calibre-"))


;;; Generated autoloads from calibre-db.el

(register-definition-prefixes "calibre-db" '("calibre-"))


;;; Generated autoloads from calibre-device.el

(register-definition-prefixes "calibre-device" '("calibre-device-"))


;;; Generated autoloads from calibre-edit.el

(register-definition-prefixes "calibre-edit" '("calibre-"))


;;; Generated autoloads from calibre-exec.el

(register-definition-prefixes "calibre-exec" '("calibre-exec--"))


;;; Generated autoloads from calibre-info.el

(register-definition-prefixes "calibre-info" '("calibre-info-"))


;;; Generated autoloads from calibre-library.el

(autoload 'calibre-library-add-book "calibre-library" "\
Add FILE to the Calibre library.

TAGS should be a list of strings to add to FILE.

(fn FILE &optional TAGS)" '(calibre-library-mode))
(autoload 'calibre-dired-add "calibre-library" "\
Add marked files to the Calibre library.

TAGS should be a list of strings to add to FILE.

(fn &optional TAGS)" '(dired-mode))
(autoload 'calibre-library "calibre-library" "\
List all books in the active Calibre Library." t)
(register-definition-prefixes "calibre-library" '("calibre-"))


;;; Generated autoloads from calibre-search.el

(register-definition-prefixes "calibre-search" '("calibre-"))


;;; Generated autoloads from calibre-util.el

(register-definition-prefixes "calibre-util" '("calibre-"))


;;; Generated autoloads from calibre-virtual-library.el

(register-definition-prefixes "calibre-virtual-library" '("calibre-"))

;;; End of scraped data

(provide 'calibre-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; calibre-autoloads.el ends here
